### ISSUE TITLE
Sanctum support (Auth::user() not working)

### ISSUE THREAD

**Issue by gtu-myowin** [munafio/chatify#197]
I am getting `Attempt to read property id` error message here and there. At first, it can be solve according to this https://github.com/munafio/chatify/issues/162#issuecomment-1067831051 .

But now the error are firing from the vendor files which are not included in published assets. Kindly let me know how to enable support for Laravel Sanctum or work around these kind of errors.

Please see the following error log for more detail.

```php
ErrorException: Attempt to read property "id" on null in file /Users/myname/code/myproject/vendor/munafio/chatify/src/ChatifyMessenger.php on line 153

#0 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(257): Illuminate\Foundation\Bootstrap\HandleExceptions-&gt;handleError(2, &#039;Attempt to read...&#039;, &#039;/Users/myname/c...&#039;, 153)
#1 /Users/myname/code/myproject/vendor/munafio/chatify/src/ChatifyMessenger.php(153): Illuminate\Foundation\Bootstrap\HandleExceptions-&gt;Illuminate\Foundation\Bootstrap\{closure}(2, &#039;Attempt to read...&#039;, &#039;/Users/myname/c...&#039;, 153)
#2 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): Chatify\ChatifyMessenger-&gt;fetchMessagesQuery(44)
#3 /Users/myname/code/myproject/app/Http/Controllers/vendor/Chatify/Api/MessagesController.php(186): Illuminate\Support\Facades\Facade::__callStatic(&#039;fetchMessagesQu...&#039;, Array)
#4 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\vendor\Chatify\Api\MessagesController-&gt;fetch(Object(Illuminate\Http\Request))
#5 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller-&gt;callAction(&#039;fetch&#039;, Array)
#6 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Routing/Route.php(268): Illuminate\Routing\ControllerDispatcher-&gt;dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\vendor\Chatify\Api\MessagesController), &#039;fetch&#039;)
#7 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Routing/Route.php(211): Illuminate\Routing\Route-&gt;runController()
#8 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\Routing\Route-&gt;run()
#9 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#12 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(126): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(102): Illuminate\Routing\Middleware\ThrottleRequests-&gt;handleRequest(Object(Illuminate\Http\Request), Object(Closure), Array)
#14 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(54): Illuminate\Routing\Middleware\ThrottleRequests-&gt;handleRequestUsingNamedLimiter(Object(Illuminate\Http\Request), Object(Closure), &#039;api&#039;, Object(Closure))
#15 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\ThrottleRequests-&gt;handle(Object(Illuminate\Http\Request), Object(Closure), &#039;api&#039;)
#16 /Users/myname/code/myproject/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(33): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful-&gt;Laravel\Sanctum\Http\Middleware\{closure}(Object(Illuminate\Http\Request))
#18 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /Users/myname/code/myproject/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(34): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#20 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#23 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Router-&gt;runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#24 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\Routing\Router-&gt;runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#25 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\Routing\Router-&gt;dispatchToRoute(Object(Illuminate\Http\Request))
#26 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\Routing\Router-&gt;dispatch(Object(Illuminate\Http\Request))
#27 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#28 /Users/myname/code/myproject/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\DisableBrowserCache-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /Users/myname/code/myproject/vendor/fruitcake/laravel-cors/src/HandleCors.php(52): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\Cors\HandleCors-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustHosts.php(48): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustHosts-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#48 /Users/myname/code/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter(Object(Illuminate\Http\Request))
#49 /Users/myname/code/myproject/public/index.php(52): Illuminate\Foundation\Http\Kernel-&gt;handle(Object(Illuminate\Http\Request))
#50 /Users/myname/.composer/vendor/laravel/valet/server.php(234): require(&#039;/Users/myname/c...&#039;)
#51 {main}
```

**Comment by munafio** [comment]
@gtu-myowin you can extend `ChatifyMessenger.php` class in your own class then override the methods you want to make change on; then in the controllers of Chatify, instead of using 
```php
// MessagesController.php
use Chatify\Facades\ChatifyMessenger as Chatify;
...
```
use your own class
```php
// MessagesController.php
use Path\to\CustomChatifyMessenger as Chatify;
...
```

**Comment by gtu-myowin** [comment]
@munafio Thank you for the work around. I thought so too. But wouldn't be nice if your package support Laravel Sanctum out of the box?

**Comment by munafio** [comment]
@gtu-myowin I will add this in the configuration file of Chatify in the next releases.
